import React, { useState, useEffect } from 'react';
import './index.css';
import jobsData from './jobs.json';

function JobCard({ job }) {
  const [expanded, setExpanded] = useState(false);

  const getScoreClass = (score) => {
    if (score >= 80) return 'score-high';
    if (score >= 60) return 'score-medium';
    return 'score-low';
  };

  return (
    <div className="job-card" onClick={() => setExpanded(!expanded)}>
      <div className="job-header">
        <div>
          <h3 className="job-title">{job.title}</h3>
          <div className="job-company">{job.company}</div>
        </div>
        <div className={`match-score ${getScoreClass(job.score)}`}>
          {job.score}
        </div>
      </div>
      
      <div className="job-details">
        {job.location && (
          <span className="detail-badge">
            📍 {job.location}
          </span>
        )}
        {job.schedule_type && job.schedule_type !== 'Unknown' && (
          <span className="detail-badge">
            ⏱️ {job.schedule_type}
          </span>
        )}
        {job.via && job.via !== 'Unknown' && (
          <span className="detail-badge">
            🏢 {job.via}
          </span>
        )}
      </div>

      {expanded && (
        <div className="job-expanded" onClick={(e) => e.stopPropagation()}>
          <div className="ai-reasoning">
            <h4>AI Match Analysis</h4>
            <p>{job.reasoning}</p>
          </div>
          
          <div className="job-description">
            {job.description}
          </div>
          
          {job.apply_link && job.apply_link !== '#' ? (
            <a 
              href={job.apply_link} 
              target="_blank" 
              rel="noopener noreferrer"
              className="apply-button"
            >
              Apply Now
            </a>
          ) : (
            <span className="apply-button" style={{ opacity: 0.5, cursor: 'not-allowed', textAlign: 'center', display: 'inline-block' }}>
              No Direct Link Available
            </span>
          )}
        </div>
      )}
    </div>
  );
}

function App() {
  const [jobs, setJobs] = useState([]);

  useEffect(() => {
    // In a real deployed static site, jobsData would be imported from the JSON file
    // generated by the scraper.
    setJobs(jobsData || []);
  }, []);

  return (
    <div className="app-container">
      <header className="header">
        <h1>Career Match</h1>
        <p>Your daily curated entry-level Data & Business Analyst opportunities in NYC.</p>
      </header>
      
      <main>
        {jobs.length === 0 ? (
          <div style={{ textAlign: 'center', color: 'var(--text-secondary)' }}>
            No jobs found for today or scraper is still running...
          </div>
        ) : (
          <div className="jobs-grid">
            {jobs.map((job) => (
              <JobCard key={job.id} job={job} />
            ))}
          </div>
        )}
      </main>
    </div>
  );
}

export default App;
